name: Merge release
description: Merge a release into the given base branch

inputs:
  GH_TOKEN:
    description: GitHub token
    required: true
  BASE:
    description: Base branch
    required: true

runs:
  using: "node20"
  main: "dist/main.js"


