name: Merge release
description: Merge a release into the given base branch

inputs:
  GH_TOKEN:
    description: GitHub token
    required: true
  BASE:
    description: Base branch
    required: true

outputs:
  merged:
    description: Whether the release was merged
    value: ${{ steps.merge.outputs.merged }}

runs:
  using: composite
  steps:
    - name: Install Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: Run main.ts
      shell: bash
      run: deno run --allow-env --allow-read --allow-write  --allow-net .github/actions/merge-release/main.ts

