name: Merge to production branch on release

on:
  release:
    types:
      - released

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Merge
        uses: ./.github/actions/merge-release/action.yml
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE: "production"
